backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogPost.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
